### ISSUE TITLE
unable to plan/apply when a comment is updated in bitbucket

### ISSUE THREAD

**Issue by shettypriy** [pavan-kumar-99/medium-manifests#25]
Hi
I have followed the link https://medium.com/nerd-for-tech/terraforming-the-gitops-way-9417cf4abf58 for doing a setup of atlantis server on EKS. When a PR is created it does do a initial init, plan. But, when I comment atlantis plan/atlantis apply on the commit it does not do anything. Following is my repo config 
```
repoConfig: |
  ---
  repos:
  - id: /.*/
    branch: /.*/
    apply_requirements: [approved, mergeable] 
    workflow: default
    allowed_overrides: []
    allow_custom_workflows: false
  workflows:
    default:
      plan:
        steps: [init, plan]
      apply:
        steps: [apply]
```
Would you be able to help me on this
